# This workflow validates the code, runs lints and prettier
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Validate code

on:
  push:
    branches: [site]
  pull_request:
    branches: [site]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: npm ci
      - run: npm run validate
      - run: npm run lint
      - run: npm run prettier
      - run: npm run build --if-present
